### ISSUE TITLE
Work in stable rust

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wee_alloc#57]
### Summary

Now that [`GlobalAlloc`](https://doc.rust-lang.org/nightly/core/alloc/trait.GlobalAlloc.html) is in stable Rust, we should cfg-off the Alloc implementation such that `wee_alloc` can be used as a global allocator in stable rust.

https://blog.rust-lang.org/2018/08/02/Rust-1.28.html

### Motivation

Stabilize all the things!

### Details

Will need to introduce a `nightly` cargo feature to turn on the `Alloc` implementation. Since the `GlobalAlloc` implementation proxies to the `Alloc` implementation, we will need to do some light refactoring to move those proxied methods into normal, non-trait methods on `WeeAlloc`.

This could be a good issue for someone who wants to dive into the code base for the first time!

**Comment by creativcoder** [comment]
I'd like to take a stab at this

**Comment by rexto** [comment]
I'd like to help as well

**Comment by fitzgen** [comment]
Since @creativcoder left a comment first, I think we should allow them to work on it. Unfortunately, there isn't too much that can be broken down into smaller parts that can be done concurrently here. Sorry @rexto!

**Comment by RReverser** [comment]
I might be missing something, but looks like this issue should not be closed as it wasn't resolved - compilation on stable still fails due to usages of `#![feature(...)]`.

**Comment by pepyakin** [comment]
Yes, seems like `alloc` crate itself is not stable still.

**Comment by RReverser** [comment]
It should be possible to modify wee_alloc to not rely on alloc crate (the only unstable thing it uses from it seems to be AllocErr which can be polyfilled depending on `feature = "nightly"`).

**Comment by RReverser** [comment]
Although there is also `core::arch::wasm32::grow_memory`, not sure what to do about that one.

**Comment by fitzgen** [comment]
Oops, I had some uncommitted work in my local copy that makes this work on stable for non-wasm targets (on wasm we still need nightly to get `grow_memory`). Will whip up a PR in a second!

**Comment by fitzgen** [comment]
Er wait no it is this PR: https://github.com/rustwasm/wee_alloc/pull/65

**Comment by RReverser** [comment]
@fitzgen But WASM should be able to at least use statically allocated memory block, right?

**Comment by RReverser** [comment]
I was thinking of something like `static_array_backend` but with proper WASM, that is using real provided memory block from JS host and not static built-in array (which blows up size of generated WASM).

**Comment by fitzgen** [comment]
We could make a static array backend on wasm stable -- combining the two in the current implementation won't do that right now.

Shelling out to JS to grow memory is also feasible, but would be a bit of a pain for configuration, at least right now.

> (which blows up size of generated WASM).

This should be incredibly compressable, though, and compressed size is what really matters.

**Comment by RReverser** [comment]
> This should be incredibly compressable, though, and compressed size is what really matters.

If you mean for network delivery, sure. If you need to host bunch of generated WASMs on a hosting with a limited disk space or have CDN do some transformations on top of it etc. etc. then there are more issues.

**Comment by RReverser** [comment]
> instead to be able to use memory passed to WebAssembly instantiation via imports object

Just a small update - I quickly checked and it's possible to do nowadays by passing `-Clink-args=--import-memory` to rustc.

Then for such config all the caller needs to do is make sure to pass a sufficient amount of memory, and WASM doesn't have to contain a hardcoded static array inside anymore.

**Comment by RReverser** [comment]
Looks like this was fixed somehow?

**Comment by fitzgen** [comment]
Yes! Everything should be working on stable since 1.30 or so!
