### ISSUE TITLE
CI should be running tests

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wee_alloc#72]
Looks like tests are currently failing on master on Unix/Windows, and it's easy to miss because CI runs just `cargo check`.

**Comment by RReverser** [comment]
Hmm how was #69 not caught by CI then? Doesn't seem anything platform-specific. And after that I found one more doc-test failure too, not reported yet.

**Comment by fitzgen** [comment]
The tests are running: https://travis-ci.org/rustwasm/wee_alloc/jobs/461412347#L479-L941

I'm not sure what was up with the layout thing, but it might have had to do with the cargo features bug.

**Comment by RReverser** [comment]
Hmm, that could be it...

**Comment by fitzgen** [comment]
I think we are only testing teh `test` crate in CI, not the `wee_alloc` crate itself (which only has a couple little tests). I'll whip up a PR.

**Comment by RReverser** [comment]
Ah that explains it.
