### ISSUE TITLE
Panicky wasm from Vec allocation

### ISSUE THREAD

**Issue by holygits** [rustwasm/wee_alloc#77]
### Summary
Some panic related code is showing in a wasm binary produced with wee_alloc.
I'm unsure if this is just panic related boiler plate or a low-level error.

### Steps to Reproduce
Using `wee_alloc = "0.4.2"` and `rustc 1.33.0-nightly (c2d381d39 2019-01-10)`
Compile to wam: `cargo build --release --target=wasm32-unknown-unknown`
Inspect wasm binary: `wasm-objdump -x </path/to/binary.wasm>`

```
// main.rs
#![feature(alloc_error_handler)]
#![feature(core_intrinsics)]
#![feature(alloc)]
#![no_std]

extern crate wee_alloc;

extern crate alloc;
use alloc::vec::Vec;

use core::intrinsics;

#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[panic_handler]
#[no_mangle]
pub fn panic(_info: &::core::panic::PanicInfo) -> ! {
    unsafe {
        intrinsics::abort();
    }
}

#[alloc_error_handler]
pub fn oom(_: ::core::alloc::Layout) -> ! {
    unsafe {
        intrinsics::abort();
    }
}

#[no_mangle]
pub extern "C" fn call() {
    let mut v: Vec<u8> = Vec::new();
    v.push(1u8);
    v.resize(10 as usize, 0u8);
}

#[no_mangle]
pub extern "C" fn deploy() {}
```

### Actual Results
Full wasm-objdump here: https://pastebin.com/XvNy29es

Some output of interest:
```
<_ZN130_$LT$wee_alloc..size_classes..SizeClassAllocPolicy$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$wee_alloc..AllocPolicy$LT$$u27$a$GT$$GT$32should_merge_adjacent_free_cells17ha5f8c5ccc562923dE>
 - func[27] <_ZN4core3ptr18real_drop_in_place17hc97ddcf593c971bfE>
 - func[28] <_ZN4core9panicking5panic17h654d1775d6e26cbdE>
 - func[29] <_ZN4core9panicking9panic_fmt17h77387da9b048cc4bE>
 - func[30] <_ZN36_$LT$T$u20$as$u20$core..any..Any$GT$11get_type_id17ha3646d193330ce0cE>
# ...
 - segment[1] size=40 - init i32=1049604
  - 0100404: 7372 632f 6c69 6261 6c6c 6f63 2f72 6177  src/liballoc/raw
  - 0100414: 5f76 6563 2e72 7363 6170 6163 6974 7920  _vec.rscapacity
  - 0100424: 6f76 6572 666c 6f77                      overflow
```

### Expected Results
No panicky related code blocks

**Comment by fitzgen** [comment]
If you use the default allocator, do you get the panic code in the binary as well? If so, then I think it is the vec code that is bringing the panicking code in, not wee_alloc.

You can also look into using twiggy to see who calls the panicking functions: https://github.com/rustwasm/twiggy

**Comment by holygits** [comment]
Thanks @fitzgen for the twiggy pointer.

Turns out it is related to `alloc::raw_vec`, I'm able to solve this by explicit bounds checking that `wanted_capacity <= isize::max_value()`

Based on this comment here:
https://github.com/rust-lang/rust/blob/14ea6e50c1534a23cb51375552c14568db9ee130/src/liballoc/raw_vec.rs#L132
