### ISSUE TITLE
Storage at arbitrary address

### ISSUE THREAD

**Issue by athei** [rustwasm/wee_alloc#82]
### Motivation

I want to place the memory pool at some arbitrary address because my embedded device happens to have some accessible memory there. The embedded static array is too inflexible for that.

### Proposed Solution

Adding another constructor to the WeeAlloc struct where I can just pass in pointer + length or a slice and this memory is used no questions asked.

**Comment by fitzgen** [comment]
I believe that this is basically asking for the same feature as https://github.com/rustwasm/wee_alloc/issues/44 ?

**Comment by athei** [comment]
Yes I guess its a subset of #44.
